### ISSUE TITLE
Manage Spreadsheet.set_value() on sparse Ranges

### ISSUE THREAD

**Issue by iOiurson** [anthill/koala#72] opened 2016-07-20 16:03 UTC
Ranges with empty cells end up being sparse Ranges (meaning they lack some Cell references).
Then using `Spreadsheet.set_value()` might result in setting incorrect values on Cells.

**Comment by danielsjf** [comment] 2019-05-16 09:40
I cannot reproduce this after the last modifications to the ranges. Let's reopen it if there is a reproducible example in the future.

@brianmay, I apparently don't have the permissions to close it.

**Closed** 2019-05-16 12:20 UTC
Labels: Bug, Enhancement
